name: Jekyll Site Build & Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: my-awesome-site

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Build
      run: bundle exec jekyll build
    - name: Upload to blob storage
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: ls && pwd && az storage blob upload-batch -d '$web' -s '_site' --connection-string ${{ secrets.BLOB_CONNECTION_STRING }}
